# pubspec.yaml
name: ui_components
description: Figma-accurate food UI
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  flutter_bloc: ^9.0.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/bell.png
    - assets/bread.png
    - assets/cabbage.png
    - assets/food_banner.png
    - assets/gradient_food-banner.png
    - assets/inactive_bookmark.png
    - assets/location.png
    - assets/new_food1.png
    - assets/new_food2.png
    - assets/new_food3.png
    - assets/profile.png
    - assets/search-normal.png
    - assets/setting.png
    - assets/star.png
    - assets/taco.png
    - assets/timer.png
    - assets/tomatos.png
    - assets/user1.png
    - assets/user2.png
    - assets/data/list.json
    - assets/data/details.json
